In [2]:
#create a decision treee

import pandas as pd

df=pd.read_csv("fish.csv")
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [8]:
x=df.iloc[:,1:7]
y=df.iloc[:,0]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="entropy",max_depth=11)
m=model.fit(x_train,y_train)
print(model.get_depth())

y_pred=model.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Error Rate:", (1-(accuracy_score(y_test,y_pred))))
print("Classification report \n", classification_report(y_test,y_pred))

11
[[10  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  4  0  5  0  0]
 [ 0  0  1  2  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  0  0  5  0]
 [ 1  1  1  0  0  0  0]]
Accuracy: 0.6875
Error Rate: 0.3125
Classification report
               precision    recall  f1-score   support

       Bream       0.91      1.00      0.95        10
      Parkki       0.50      1.00      0.67         1
       Perch       0.57      0.44      0.50         9
        Pike       1.00      0.67      0.80         3
       Roach       0.00      0.00      0.00         1
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.69        32
   macro avg       0.57      0.59      0.56        32
weighted avg       0.71      0.69      0.69        32

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [11]:
x=df.iloc[:,1:]
y=df.iloc[:,0]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=13)
knn.fit(x_train, y_train)
pred=knn.predict(x_test)

# from sklearn.linear_model import LinearRegression
# model=LinearRegression()
# model.fit(x_train, y_train)
# pred=model.predict(x_test)

#confusion metrices
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,pred)
cm

print("Accuracy:",accuracy_score(y_test,pred))
print("Error Rate:",(1-accuracy_score(y_test,pred)))

Accuracy: 0.65625
Error Rate: 0.34375

In [15]:
#Random forest classifier

x=df.iloc[:,1:7]
y=df.iloc[:,0]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=10)
m=rf.fit(x_train,y_train)

from sklearn import tree
y_pred=rf.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Error Rate:", (1-(accuracy_score(y_test,y_pred))))
print("Classification report \n", classification_report(y_test,y_pred))

[[10  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0]
 [ 0  0  6  0  3  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  1  0  2  0  0]]
Accuracy: 0.78125
Error Rate: 0.21875
Classification report
               precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        10
      Parkki       1.00      1.00      1.00         1
       Perch       0.75      0.67      0.71         9
        Pike       1.00      1.00      1.00         3
       Roach       0.00      0.00      0.00         1
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.78        32
   macro avg       0.68      0.67      0.67        32
weighted avg       0.80      0.78      0.79        32

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [2]:
import pandas as pd

df=pd.read_csv("iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
x=df.iloc[:,1:5]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=10)
m=rf.fit(x_train,y_train)

from sklearn import tree
y_pred=rf.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Error Rate:", (1-(accuracy_score(y_test,y_pred))))
print("Classification report \n", classification_report(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Error Rate: 0.0
Classification report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [1]:
#PB_226
#  Write a program to create a Model using linear regression to predict the charges of insurance using the csv file provided named 
# “insurance.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and 
# mean squared error.

import pandas as pd
df=pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
x=df.iloc[:,1:6]
y=df.iloc[:,-1]

x=pd.get_dummies(x,drop_first=True)
x

,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,27.900,0,False,True,False,False,True
1,33.770,1,True,False,False,True,False
2,33.000,3,True,False,False,True,False
3,22.705,0,True,False,True,False,False
4,28.880,0,True,False,True,False,False
...,...,...,...,...,...,...,...
1333,30.970,3,True,False,True,False,False
1334,31.920,0,False,False,False,False,False
1335,36.850,0,False,False,False,True,False
1336,25.800,0,False,False,False,False,True
1337,29.070,0,False,True,True,False,False

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import mean_squared_error,r2_score
print("mse: ",mean_squared_error(y_test,y_pred))
print("r2score: ",r2_score(y_test,y_pred))

mse:  46728092.87381381
r2score:  0.6990114352316631

In [8]:
print("coefficient: ",model.coef_)
print("intercept: ",model.intercept_)
print("Predicted Values:",y_pred)

coefficient:  [  413.87783473   607.04461791   -78.95782383 23211.13577157
  -219.17044513  -919.59849701  -691.16809011]
intercept:  -4240.224713639056
Predicted Values: [ 7393.23901144  7965.21743974 29878.84619944  7938.06572617
 31883.76327346 13352.05310012  4859.06429011 11149.68634273
  2915.7230488   9156.93594945 30120.53816506  9336.25921752
  7693.86653684 37321.21489152 34908.23573413 35302.84685719
 13718.57201133 33818.70226489  7056.49467136 29878.84619944
  7916.55271194  9696.15602034  7571.53554813 12234.18249768
  8999.98340748  9285.30292525  9595.71919518  9943.62487066
  7983.01492592  7235.4969042   9623.40622539  8712.26693142
  9272.09688629  5618.60149776  8013.02903214 12155.22467385
  6602.02665096  8050.5990725  29345.65738268 33147.8991374
  9940.73635899  9043.761754   10492.47829739  5998.97668955
 10771.44079284  6978.33444532 10673.40565892  6946.97243385
 34680.67430596 11864.07827652  9863.94218995  7523.85558937
 13290.46937354  6493.37589478  9011.03281518 10184.52397144
  6218.14713469 34727.17537896  8767.96352572  9521.21329104
  8229.92234058 13900.67825861 11751.7730598   7095.43177771
  8538.25343357  6881.57110279 31265.62396811  7508.72765604
  5466.10890802 11337.82384414 11622.03585708 10342.11858387
  8634.72502081  9360.11737642 11120.45397315  7223.40160439
 10988.16056084  6156.57130198  9712.23457117  7526.40140246
  8555.76719698 29940.42203215  8616.25590694 35361.9004932
 40341.09590496 32063.6153243   9648.47606158  9026.49305058
  9454.53543565 11958.71197716 12740.54063611 27566.3639813
 30390.51410809  8336.55943938 33375.5319465   9530.60488645
 30552.88511366  8498.14533535 30363.154647    6685.50791405
  7903.84935456  7029.67661987 11423.94059164 11751.7730598
  5471.097643    9936.76336583  8677.21894912 26622.40148289
  4566.77457412 28127.88203739  8689.00570189 14625.99923329
  9774.39236026 32788.93616034  9105.97965718  9254.66253632
  7515.65414656 30544.37039086  8801.70333477  7392.38919344
 10128.25790895 10830.35820089 12858.49581901  9602.87811884
  6623.61104612 10437.49529313 10197.82743694  8633.83789035
  9408.67657175 12106.83901894  6813.66254801 10786.64010708
 10895.92517849 11605.0881889   8643.8001753  10951.56165871
 10267.94174749 30617.12018581 34872.28227543 31710.07081084
  6667.71042787  9796.44205114  9420.77187156 12285.45982519
  5414.4344314  30010.14694882  8038.75220565  7112.45218681
 12420.68371151  8219.96794951 35828.41145457  7178.84955376
 11788.1530862  33417.70943389 12936.60382485 10032.0313817
  8970.43473562  7602.8134132  31754.80766874 33063.8438852
 10145.52661237  6802.93431419  6799.01117725  5824.96319169
 10344.58842172 11363.2860965  33882.93733704 31648.1739429
 32474.06797071  7609.10558849  4491.24969385  9126.68144279
 13334.77650282  6802.61327896  6284.69651736 29096.03513542
 29665.20116593 11514.99371528 27318.36958255  5134.29305021
 30451.88219327  3326.17569521  4168.28086092  9623.33484447
  6820.41076514  9341.36124021  8555.20110175  6533.02321819
 14204.1648771   6903.29975843 12165.65089452  7830.52233618
  5353.46349534 34438.63978041 10832.09528798  8953.41095355
  6291.7951883   8926.6563891   6650.97050721  5663.87976527
  4741.10910722 29996.48034711 14276.98605298  7960.11541705
 29766.83826291 28294.78897042  6392.16063254  6169.05901795
 11378.41402982  4284.31077648  3846.63503558  5372.01188402
 16868.97203752 29171.88894481  6309.83773448  7319.38321029
  7147.547795    8179.53078354  4992.60007521  9605.98213328
 10324.32109769 11818.09904582 15840.0884691  34938.63436263
  8751.26429049 31084.00454125  3594.49059163  8122.1699817
  7797.01496029 14431.86906712 10012.61717522  3011.09975806
  6464.09116636 29706.58894941  3129.05494095 10012.61717522
  9454.21440042  9102.88353662 35973.64998468  8737.87344426
  3348.22538609 34107.53751262  9813.1819718   7830.4462223
  5881.02150665  8318.7619532   7664.33688707  8633.84578423
 17224.18865239  2696.23156843  7319.39110418 11420.67079201
  5746.65533221  4960.27955235  9319.31154933  8786.50402052
  6950.71879603 10105.35840008  4999.27691141 10202.11371009
  9235.89377328  4269.28837563 30036.89361939 32495.32795767
  6785.66561077  7886.78839867 37673.26070534  9830.27376183]

In [2]:
import pandas as pd

df=pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
x=df.iloc[:,0:8]
y=df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

from sklearn.svm import SVC
svm_model=SVC(kernel="rbf",random_state=42,C=10)
svm_model.fit(x_train,y_train)
y_pred=svm_model.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("TP:",cm[1][1])
print("TN:",cm[0][0])
print("FN:",cm[1][0])
print("FP:",cm[0][1])
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Sensitivity:",recall_score(y_test,y_pred))
print("classification_report",classification_report(y_test,y_pred))

[[84 11]
 [28 31]]
TP: 31
TN: 84
FN: 28
FP: 11
Accuracy: 0.7467532467532467
Sensitivity: 0.5254237288135594
classification_report               precision    recall  f1-score   support

           0       0.75      0.88      0.81        95
           1       0.74      0.53      0.61        59

    accuracy                           0.75       154
   macro avg       0.74      0.70      0.71       154
weighted avg       0.75      0.75      0.74       154

In [13]:
import pandas as pd
df=pd.read_csv("Employee_Attrition.csv")
df

,Employee_ID,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,1,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,2,56,31395,18,HR,Poor,Yes,1,7,School,1
2,3,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,4,39,20851,5,HR,Good,No,2,7,Graduate,0
4,5,28,32156,12,Developer,Good,No,3,26,School,0
...,...,...,...,...,...,...,...,...,...,...,...
245,246,46,39369,7,Developer,Excellent,Yes,2,1,Graduate,0
246,247,42,74890,4,HR,Excellent,Yes,4,17,Postgraduate,0
247,248,52,116447,1,Manager,Excellent,Yes,3,22,Graduate,0
248,249,55,69391,10,Manager,Good,No,3,22,Postgraduate,0
249,250,38,99963,15,Manager,Poor,No,3,8,Graduate,0

In [14]:
df=df.drop("Employee_ID",axis=1)
df

,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,56,31395,18,HR,Poor,Yes,1,7,School,1
2,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,39,20851,5,HR,Good,No,2,7,Graduate,0
4,28,32156,12,Developer,Good,No,3,26,School,0
...,...,...,...,...,...,...,...,...,...,...
245,46,39369,7,Developer,Excellent,Yes,2,1,Graduate,0
246,42,74890,4,HR,Excellent,Yes,4,17,Postgraduate,0
247,52,116447,1,Manager,Excellent,Yes,3,22,Graduate,0
248,55,69391,10,Manager,Good,No,3,22,Postgraduate,0
249,38,99963,15,Manager,Poor,No,3,8,Graduate,0

In [25]:
df=pd.get_dummies(df,drop_first=True)
df

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Analyst,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Excellent,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_No,Overtime_Yes,Education_Graduate,Education_Postgraduate,Education_School
0,29,23278,8,1,22,1,False,False,False,True,False,False,True,False,True,False,True,False
1,56,31395,18,1,7,1,False,False,True,False,False,False,True,False,True,False,False,True
2,54,98907,0,2,15,0,False,False,False,True,True,False,False,True,False,False,True,False
3,39,20851,5,2,7,0,False,False,True,False,False,True,False,True,False,True,False,False
4,28,32156,12,3,26,0,False,True,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,46,39369,7,2,1,0,False,True,False,False,True,False,False,False,True,True,False,False
246,42,74890,4,4,17,0,False,False,True,False,True,False,False,False,True,False,True,False
247,52,116447,1,3,22,0,False,False,False,True,True,False,False,False,True,True,False,False
248,55,69391,10,3,22,0,False,False,False,True,False,True,False,True,False,False,True,False
249,38,99963,15,3,8,0,False,False,False,True,False,False,True,True,False,True,False,False

In [19]:
x=df[["Age","Monthly_Income","Years_at_Company","Job_Satisfaction","Distance_From_Home","Job_Role_Analyst","Job_Role_HR","Work_Life_Balance_Excellent","Work_Life_Balance_Good",
          "Work_Life_Balance_Poor","Overtime_No","Overtime_Yes","Education_Graduate","Education_Postgraduate","Education_School"]]
y=df["Attrition"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=25) #underroot (total data) 768=27.... if any even number comes then +1 or -1 and take odd number
knn.fit(x_train, y_train)
pred=knn.predict(x_test)
print(pred)

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score
cm=confusion_matrix(y_test,pred)
cm
#order[TN FP
#      FN TP]
# to find accuracy: (TP+TN)/(TP+FP+FN+TN) 

print("TP:",cm[1][1])
print("TN:",cm[0][0])
print("FN:",cm[1][0])
print("FP:",cm[0][1])
print("Accuracy:",accuracy_score(y_test,pred))
print("Sensitivity:",recall_score(y_test,pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
TP: 0
TN: 47
FN: 3
FP: 0
Accuracy: 0.94
Sensitivity: 0.0

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier,accuracy_report
rf=RandomForestClassifier(n_estimators=150,random_state=42,max_depth=12,criterion="entropy")
m=rf.fit(x_train,y_train)

from sklearn import tree
y_pred=rf.predict(x_test)

y_pred=rf.predict(x_test)
acc=accuracy_report(y_test,y_pred1)
print(acc)
cm=confusion_matrix(y_test,y_pred1)
print(cm)

ImportError: cannot import name 'accuracy_report' from 'sklearn.ensemble' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\__init__.py)

In [1]:
import pandas as pd
df=pd.read_csv("Employee_Attrition.csv")
df=df.drop("Employee_ID",axis=1)
df=pd.get_dummies(df,drop_first=True)

x=df.iloc[:,[0,1,2,3,4,6,7,8,9,10,11,12,13]]
y=df["Attrition"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score
acc_list=[]

for k in range(1,26):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    acc=accuracy_score(y_test,y_pred)
    acc_list.append(acc)
    print(f"k={k},Accuracy={acc}")
max_acc=max(acc_list)

best_k=(acc_list.index(max_acc))+1
print("------------------------------------------------------------------------------")
print("Best_k: ",best_k)

knn=KNeighborsClassifier(n_neighbors=best_k)
knn.fit(x_train,y_train)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=150,random_state=42,max_depth=12,criterion="entropy")
m=model.fit(x_train,y_train)
y_pred1=m.predict(x_test)

acc=accuracy_score(y_test,y_pred1)
print("---------------------------------------------------------------------------------")
print("Accuracy:",acc)
cm=confusion_matrix(y_test,y_pred1)
print("---------------------------------------------------------------------------------")
print(cm)

import numpy as np
x_t=np.array([30,45000,5,3,10,1,0,0,1,0,1,0,0]).reshape(1,-1)
print("Prediction for knn:",knn.predict(x_t))
print("Prediction for rf:",model.predict(x_t))

k=1,Accuracy=0.86
k=2,Accuracy=0.94
k=3,Accuracy=0.94
k=4,Accuracy=0.94
k=5,Accuracy=0.94
k=6,Accuracy=0.94
k=7,Accuracy=0.94
k=8,Accuracy=0.94
k=9,Accuracy=0.94
k=10,Accuracy=0.94
k=11,Accuracy=0.94
k=12,Accuracy=0.94
k=13,Accuracy=0.94
k=14,Accuracy=0.94
k=15,Accuracy=0.94
k=16,Accuracy=0.94
k=17,Accuracy=0.94
k=18,Accuracy=0.94
k=19,Accuracy=0.94
k=20,Accuracy=0.94
k=21,Accuracy=0.94
k=22,Accuracy=0.94
k=23,Accuracy=0.94
k=24,Accuracy=0.94
k=25,Accuracy=0.94
------------------------------------------------------------------------------
Best_k:  2
---------------------------------------------------------------------------------
Accuracy: 1.0
---------------------------------------------------------------------------------
[[47  0]
 [ 0  3]]
Prediction for knn: [0]
Prediction for rf: [0]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(